# Generated by Django 4.2.2 on 2023-09-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ColorPicker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HEX', models.CharField(max_length=50)),
                ('RGB', models.CharField(max_length=50)),
                ('CMYK', models.CharField(max_length=50)),
                ('ImageHolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColorPicker.colorpickerimageholder')),
            ],
        ),
    ]
