# Generated by Django 4.2.2 on 2023-09-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColorPicker', '0002_colorholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorholder',
            name='XYZ',
            field=models.CharField(default='', max_length=50),
        ),
    ]
