# Generated by Django 4.2.2 on 2023-10-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColorPicker', '0003_colorholder_xyz'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorholder',
            name='LAB',
            field=models.CharField(default='', max_length=50),
        ),
    ]
