# Generated by Django 4.2.2 on 2023-10-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColorPicker', '0004_colorholder_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorholder',
            name='HSV',
            field=models.CharField(default='', max_length=50),
        ),
    ]
