# Generated by Django 4.2.2 on 2023-10-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColorPicker', '0005_colorholder_hsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorholder',
            name='YUV',
            field=models.CharField(default='', max_length=50),
        ),
    ]
