# Generated by Django 4.2.2 on 2023-10-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColorPicker', '0006_colorholder_yuv'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorholder',
            name='HSL',
            field=models.CharField(default='', max_length=50),
        ),
    ]
